Start up v2
DiabetesIntegration/AndroidApp pull request #6
Opened 2017-03-10 11:21 UTC by greglaw95

Added the ability to enter typical basal insulin usage, then receive timed notifications based on this information to remind the user when to take insulin.
Added a placeholder main page to the application to allow navigation.
Added a take insulin screen to allow the user to see their current insulin recommendation and to record taking insulin. Currently it allows the user to record either basal or bolus insulin but only provides recommendations for basal.

2017-03-10 20:56 UTC, liddad commented on DMS/app/src/main/java/com/example/kbb12/dms/Model/InsulinModel.java
> +    public void saveDoses(List<BasalInsulinDose> basicDoses,String basalInsulinBrandName) throws DuplicateDoseException;
Does the insulin model only deal with basal insulin just now, or is this separated?

2017-03-10 21:14 UTC, liddad requested changes
Are MainActivity & Main2Activity used? If so, can they be renamed? 
Do we have separate Models for basal & short acting insulin? (This is fine I just want to know) And to what extent are we giving recommendations? Do we give them/ do we improve them? Do we give for basal and short-acting or only short-acting?

2017-03-11 11:13 UTC, greglaw95 commented on DMS/app/src/main/java/com/example/kbb12/dms/Model/InsulinModel.java
> +    public void saveDoses(List<BasalInsulinDose> basicDoses,String basalInsulinBrandName) throws DuplicateDoseException;
It'll be the same underlying model it's an interface for the UserModel. It probably will be separated actually this is really just the interface between the screen that takes in the basal information on first set-up and the global model.

2017-03-11 11:23 UTC, greglaw95 commented
I can't find Main2Activity anywhere. If it is in there it's probably a mistake where did you see it?

We will have separate models for the basal and bolus insulin in fact we'll probably have 3 tables which essentially make up the different mathematical models for the basal insulin, insulin to carb ratio and insulin sensitivity factors throughout the day. More than that we'll actually have duplicates of each one to hold the original values and one to hold improvements we make to it.

In this pull request we only have the table for the basal insulin set-up but there is code that will allow a duplicate to be set-up using an almost identical contract very quickly. At the moment the "recommendations" are essentially just what the user tells us on first start up. A notification is fired at the times they said they take insulin. The recommendation in the take insulin page is based on the last dose of insulin they were supposed to take but haven't registered as having taken in the take insulin page yet.

2017-03-13 19:38 UTC, liddad approved these changes

2017-03-13 19:39 UTC, merged